### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by kirillMalets** [robohydra/robohydra#10]
Getting error when running Robohydra. This a screenshot https://www.dropbox.com/s/c0axz08rlyqm0dc/Screenshot%202015-01-12%2011.35.00.png?dl=0

Tried to reinstall robohydra few times, no luck.

Thanks in advance for help.

**Comment by emanchado** [comment]
Agh, sorry, my bad. I totally forgot about case-insensitive filesystems and in the last release I introduced a new file that only differs from another one in casing.

For now you can use RoboHydra 0.5.0. I'll fix and release soon, thanks for the heads up!

**Comment by emanchado** [comment]
Can you please download the latest code from the master branch and confirm that it works fine?

**Comment by kirillMalets** [comment]
I've tested it now. Everything works fine! Thanks for help.

**Comment by emanchado** [comment]
Released 0.5.1a, should fix the issue. Thanks!

**Comment by Qantas94Heavy** [comment]
Could you release it as `0.5.2` instead? This breaks npm's version system as `0.5.1` is considered to be higher than `0.5.1-a`. Thanks!

**Comment by emanchado** [comment]
Agh, forgive my stupid. I think it's not even the first time it happens to me. Released now as 0.5.2, thanks for the tip!
