### ISSUE TITLE
[1]    2065 segmentation fault  robohydra robohydra.conf

### ISSUE THREAD

**Issue by brngdsn** [robohydra/robohydra#15]
Hi. I just upgraded to node v4.0.0 and as you can see it's choking.

**Comment by brngdsn** [comment]
Looks like I had to reinstall the global package after the upgrade,

**Comment by emanchado** [comment]
Oh, good to know :-) I was checking now and I didn't see it fail, so I wondered if it had to do with the specific configuration you were using.

But, it's probably a good idea to NOT install RoboHydra globally. At least if you're under some kind of Unix, it's IMO nicer to add ./node_modules/.bin to the $PATH and always install local...
