### ISSUE TITLE
Default plugin configuration problem

### ISSUE THREAD

**Issue by pongracz** [robohydra/robohydra#20]
We would like to use the new default plugin configuration (_pluginConfigDefaults_), but we found some problems in it:

- When the config defaults are setted up, and we use a config variable with the same name, but with different values in the plugins, the last setted value is used in every plugin.
- If a plugin have a path config, every plugin use that value.

Example:
```
{
	"pluginConfigDefaults" : {
		"timeout" : 10000
	},
	"plugins" : [{
			"name" : "plugin1",
			"config" : {
				"URLRedirection" : "http://something",
				"path": "plugins/plugin1"
			}
		}, {
			"name" : "plugin2",
			"config" : {
				"URLRedirection" : "http://something_else"
			}
		}
	]
}
```
In this example, the plugin2 also get the plugin1's path config, and the plugin1 is also using the "http://something_else" URLRedirection.

**Comment by emanchado** [comment]
How embarrassing! :-) Thanks, I'll fix soon and will try to release this weekend...

**Comment by emanchado** [comment]
I have a fix in master, feel free to use that until I make a proper release.
