### ISSUE TITLE
Automatic conversion of post-body

### ISSUE THREAD

**Issue by bbultman** [robohydra/robohydra#22]
Hello there! Love robohydra, it's been an invaluable tool for me lately :-)

The standard way to handle post-body is to return it as a rawBody property on the request object. Of course this is most flexible, but I wonder if there is any reason why we don't automatically parse it if a given header is present:

For example: A request with the "content-type: application/json" header could provide some ready-to-use-json inside the request object.

**Comment by emanchado** [comment]
Thanks, glad it's useful :-) Can I ask what you use it for?

You're right, JSON parsing is common enough that it should probably be granted special treatment. I want to keep rawBody as-is but in the same way we have bodyParams, I can maybe add jsonBody or similar.

Want to give it a shot, or should I try to implement it?

**Comment by bbultman** [comment]
Exactly as I thought!

Using it to mock (mostly static data) an existing API for testing purposes. Recently been using it to do really quick POCs for new features so clients have something to build against without the need for a production-scale backend to be finished already. Works really well for both use-cases. Planning to investigate the client-testing functionality, though it will probably have to wait a while.

I'd like to contribute, so I'll see if I can get this done soon :-)

**Comment by emanchado** [comment]
Cool. Do you have a single installation for all clients, or do they run their own private RoboHydra? If the latter, have you used scenarios? I think it's one of the coolest features but I have the impression that people don't know it or understand it. If it's the former, you can still do it with summoners, but it's harder.

Looking forward to your patch!

**Comment by bbultman** [comment]
Single installation, running inside a docker container, behind nginx (as a reverse proxy). Works great! Some devs choose to run it locally, but that's only because it's a lot faster (~1ms vs ~200ms response times), since the host machine is currently overseas.

We're using summoners, implemented like your example - where you use a header to call a specific hydra. It was actually very easy, just have to get the clients to generate a random ID on startup (using 10-digit alphanumeric iirc).

I haven't really setup scenarios, but it's something we'll be looking at soon I think. It wasn't the lowest-hanging fruit and we have some quite non-trivial flows.

The patch is mostly in place, it got... slightly bigger than planned. I still want to try to make it easier to read, and write tests before I submit it though.
