### ISSUE TITLE
can't run test on forked code

### ISSUE THREAD

**Issue by cuongluu8** [robohydra/robohydra#25]
I just forked the code and trying to run the test.  
Just executing `npm test`
I get the following error.

```
> buster-test

Failed requiring ./test/plugins-test.js: Cannot find module 'robohydra'
npm ERR! Test failed.  See above for more details.
```

**Comment by emanchado** [comment]
Yes, sorry, this was my first project and some things were set up in a silly way.

Try again with the updated master, hopefully my fix just now was enough. Thanks for the heads up!
