### ISSUE TITLE
Not compatible with MIME 2.0.2

### ISSUE THREAD

**Issue by DavidZWL** [robohydra/robohydra#28]
`"mime": ">= 1.0.0"` in package.sjon is causing runtime exception as it resolves to mime@2.0.2. mime@2.0.2 replaced `lookup()` to `getType()`.

**Comment by emanchado** [comment]
Thanks for the report. For now I just tightened the dependency. I hope to release a new version with this fix soon!

**Comment by DavidZWL** [comment]
Thanks for the quick reaction. I suggest tighten up the other dependencies as well, `>=` is too risky.

**Comment by emanchado** [comment]
Yes, thanks. I'm not sure why I didn't do it right away, but the change is on `master` now so it will be part of the next release :-)
